### ISSUE TITLE
Fluid url: the mod doesn't work anymore when I customize the toolbar

### ISSUE THREAD

**Issue by myamusashi** [wysh3/Zen-Mods#1]
To reproduce this, just edit the toolbar

**Comment by wysh3** [comment]
could you share a video of the issue you're experiencing?
please disable all mods and custom css before recording.

**Comment by myamusashi** [comment]
I'll create a new profile for that.

**Comment by myamusashi** [comment]
https://github.com/user-attachments/assets/4bc1b5ab-1c9d-4d39-9817-50070886bed8
Here you go.

**Comment by wysh3** [comment]
https://github.com/zen-browser/theme-store/pull/921
The issue occurred because of removing reload button from the tootlbar, which was a dependency for the animation. I've submitted a PR, and it will be fixed once merged.

**Comment by myamusashi** [comment]
Oh good, I'll close it then
